title: Thinqat
author: Thinqat (Thinqat1985731)
description: 
show_excerpts: true # set to true to show excerpts on the homepage

# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Thinqat
  tagline: A certain universiry student (B3)
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  portfolio_image: "assets/icon.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "jp" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  social_links:
    #twitter: jekyll
    github:  Thinqat1985731
    #linkedIn: jekyll
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    #email: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

  navigation:
    - title: About Me
      url: /myblog/about/

# Build settings
remote_theme: samarsault/plainwhite-jekyll

plugins:
  - jekyll-seo-tag
  #- jekyll-feed
